.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ACPIDUMP 1 "June 2, 2013"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
acpidump \- ACPI table dump utility
.SH SYNOPSIS
.B acpidump
.RI [ <option> ... ]

.SH DESCRIPTION
This manual page is currently a placeholder for the ACPICA version
of the
.B acpidump.
command.  At present, the command is not implemented and a stub
command has been include in the upstream source.  When a full
implementation is available, this man page will be updated with
the proper information.

.SH AUTHOR
acpidump was written by Robert Moore <robert.moore@intel.com> and
Chao Guan <chao.guan@intel.com>.
.PP
This manual page was written by Al Stone <ahs3@redhat.com> for the
Fedora project (but may be used by others).
